// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026/2/27 11:22:24
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/xinre/Desktop/15/Juxing-Space-Station/钟元智库/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/xinre/Desktop/15/Juxing-Space-Station/钟元智库/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/xinre/Desktop/15/Juxing-Space-Station/钟元智库/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/xinre/Desktop/15/Juxing-Space-Station/钟元智库/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/xinre/Desktop/15/Juxing-Space-Station/钟元智库/plugins/**/*.{js,ts,mjs}","C:/Users/xinre/Desktop/15/Juxing-Space-Station/钟元智库/composables/**/*.{js,ts,mjs}","C:/Users/xinre/Desktop/15/Juxing-Space-Station/钟元智库/utils/**/*.{js,ts,mjs}","C:/Users/xinre/Desktop/15/Juxing-Space-Station/钟元智库/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/xinre/Desktop/15/Juxing-Space-Station/钟元智库/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/xinre/Desktop/15/Juxing-Space-Station/钟元智库/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/xinre/Desktop/15/Juxing-Space-Station/钟元智库/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;